SNTH-23
Dillxn/tactile-synth pull request #8
Opened 2023-02-13 02:33 UTC by GrizzlyJay

2023-02-13 04:48 UTC, MattRas10 approved these changes

2023-02-13 15:04 UTC, Dillxn requested changes
Please see comments

2023-02-13 15:04 UTC, Dillxn commented on app/src/main/java/com/dillxn/tactilesynth/MainActivity.java
> +    // JOSH - POPULATES DEBUG TEXTVIEWS FOR EFFECTS ON APP STARTUP
I do wish we had a more minimal MainActivity.java, with this and other stuff moved to other appropriate classes.

2023-02-13 15:04 UTC, Dillxn commented on app/src/main/java/com/dillxn/tactilesynth/MainActivity.java
> +                if (b) {
What does `b` here represent?

2023-02-15 19:32 UTC, GrizzlyJay commented on app/src/main/java/com/dillxn/tactilesynth/MainActivity.java
> +                if (b) {
links the check boxes to the list of selected effects if I recall correctly.

2023-02-15 19:33 UTC, GrizzlyJay commented on app/src/main/java/com/dillxn/tactilesynth/MainActivity.java
> +    // JOSH - POPULATES DEBUG TEXTVIEWS FOR EFFECTS ON APP STARTUP
currently working on this.

2023-02-15 21:13 UTC, Dillxn commented on app/src/main/java/com/dillxn/tactilesynth/MainActivity.java
> +                if (b) {
Can we name this something clearer?

2023-02-20 18:52 UTC, closed without merging

2023-02-20 18:53 UTC, GrizzlyJay commented
Pull request outdated by progress